version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
